__author__ = 'Joseph'

from selenium import webdriver
import unittest

class NewVisitorTest(unittest.TestCase):

    def setUp(self):
        self._browser = webdriver.Firefox()
        self._browser.implicitly_wait(3)

    def tearDown(self):
        self._browser.quit()

    def test_can_read_faq_and_documentation(self):
        # User has been instructed to visit genome simulator site to read
        # project documentation. User goes to check out its homepage
        self._browser.get('http://localhost:8000')

        # She notices the words 'Genome Simulator' are in the page title
        self.assertIn('Documentation', self._browser.title)

        # She sees menu has links to the following sections right away

        # She decides to first read the FAQ
        self.assertIn('FAQ', self._browser.title)

        # She then goes to the documentation and reads through all of it
        self.assertIn('Documentation', self._browser.title)

    def test_can_download_genome_data(self):
        # User has been instructed to download genome data. User goes to the homepage
        self._browser.get('http://localhost:8000')

        # Next she clicks on "Downloads" and downloads the data files for a warmup genome
        self.assertIn('Downloads', self._browser.title)

    def test_answer_file_submission_and_nickname_update(self):
        # User wishes to submit an answer file for eval. User goes to the homepage
        self._browser.get('http://localhost:8000')

        # Next she clicks on "Upload Files" and uploads the answer file for the warmup genome
        self.assertIn('Uploads', self._browser.title)

        # She then submits the answer file generated by her algorithm and is directed
        # to the queue

        # She waits 30 seconds and then clicks on "Scores"

        # She sees her results posted with the following scores:

        # She doesn't like the name listed so she clicks the "Nickname" link
        self.assertIn('Nickname', self._browser.title)

        # She enters a new nickname and clicks 'submit'

        # She goes to Scores and sees her name has changed


if __name__ == '__main__':
    unittest.main(warnings='ignore')
