__author__ = 'Joseph'

from selenium import webdriver

browser = webdriver.Firefox()

# User has been instructed to visit genome simulator site to read
# project documentation. User goes to check out its homepage
browser.get('http://localhost:8000')

# She notices the words 'Genome Simulator' are in the page title
assert 'Genome Simulator' in browser.title

# She sees menu has links to the following sections right away

# She decides to first read the FAQ

# She then goes to the documentation and reads through all of it

# Next she goes and downloads the data files for a warmup genome

# She then submits the answer file generated by her algorithm and is directed
# to the queue

# She waits 30 seconds and then clicks on "Scores"

# She sees her results posted with the following scores:

# She doesn't like the name she has listed, so she clicks on the link for 'Nicknames'

# She enters a new nickname and clicks 'submit'

# She goes back to Scores and sees her name has changed

# She then closes her browser
browser.quit()
